// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uakxtdrwrpccruhxevkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVha3h0ZHJ3cnBjY3J1aHhldmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDQ5MjcsImV4cCI6MjA2NjM4MDkyN30.drC_atkkR6LiZwf4Pid3I0bh-0kus9B_9roqJeZttSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);